version: '2'

services:
  nginx-rtmp:
    # build: .
    image: dockerregistry.metaways.net/ebhh/docker-livestream-rtmp-nginx:${IMAGE_VERSION_TAG}
    mem_limit: 3500m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2k"
        max-file: "10"
    ports:
      - 1935:1935
      - 8443:80
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf.lua:/usr/local/share/lua/5.1/conf.lua
      - $PWD/html:/usr/local/nginx/html
