version: '2'

services:
  nginx-rtmp:
    build: .
    mem_limit: 3500m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2k"
        max-file: "10"
    ports:
      - 1935:1935
      - 80:80
      - 443:443
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - RTMP_PORT=1935
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf.lua:/usr/local/share/lua/5.1/conf.lua
      - $PWD/html:/usr/local/nginx/html
